pipeline {
    agent {
        docker {
            image "ruby:alpine"
            args "--network=skynet"
        }
    } 
    stages {
        stage("Build") {
            steps {
                sh "chmod +x jenkins4testers/build/alpine.sh"
                sh "./jenkins4testers/build/alpine.sh"
                sh "bundle install"
            }
        }
        stage("Tests") {
            steps {
                sh "bundle exec cucumber -p ci"
            }
        }
    }
}