---
  url: 'http://hmg.nflix.com'
  database: 
    host: '10.30.40.1'
    dbname: 'nflix'
    user: 'postgres'
    password: 'qaninja'
  users:
    cat_manager:
      email: 'tony@stark.com'
      password: '123456'